version: '3.2'
services: 
    speedtest-influxdb:
        image: 'influxdb:1.8'
        container_name: 'speedtest-influxdb'
        ports:
            - 8086:8086
        environment: 
          DOCKER_INFLUXDB_INIT_USERNAME: "admin"
          DOCKER_INFLUXDB_INIT_PASSWORD: "admin"
          DOCKER_INFLUXDB_INIT_ORG: "speedtest_telegraf"
          DOCKER_INFLUXDB_INIT_BUCKETS: "Speedtest"
          DOCKER_INFLUXDB_INIT_MODE: setup
        volumes: 
          - './speedtest/conf/influxdb.conf:/etc/influxdb/influxdb.conf'
          - './db/influxdb:/var/lib/influxdb'
        networks: 
          - influxdb-network
    speedtest-telegraf:
        image: 'telegraf'
        container_name: 'speedtest-telegraf'
        volumes: 
            - type: bind
              source: ./speedtest/conf/telegraf.conf
              target: /etc/telegraf/telegraf.conf
            - type: bind
              source: ./speedtest/bin
              target: /speedtest
        networks: 
          - influxdb-network
    speedtest-grafana:
        image: 'grafana/grafana'
        container_name: 'speedtest-grafana'
        user: root
        ports:
          - 3000:3000
        environment: 
          GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN:-localhost}
          GF_RENDERING_SERVER_URL: http://speedtest-grafana-renderer:8081/render
          GF_RENDERING_CALLBACK_URL: http://speedtest-grafana:3000/
          GF_LOG_FILTERS: rendering:debug
        volumes: 
            - ./db/grafana:/var/lib/grafana
        networks: 
          - influxdb-network
          
    speedtest-grafana-renderer:
        image: 'grafana/grafana-image-renderer'
        container_name: 'speedtest-grafana-renderer'
        ports:
          - "8081:8081"
        networks: 
          - influxdb-network
networks: 
  influxdb-network:

